Hafele_Onam/Hafele_Onam/Controllers/LoginController.cs
using Hafele_Onam.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Hafele_Onam.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/
        Utility util = new Utility();

        [HttpGet]
        public ActionResult Index(string Usertype)
       {
            Login log = new Login();
            if (Usertype == "SuperAdmin")
            {
                ViewBag.Title = "Super Admin Login";
            }
            else
            {
                ViewBag.Title = "Billing Login";
            }
            log.UserType = Usertype;
            return View(log);
        }




        #region Generic Login Code
        [HttpGet]
        public ActionResult Login(string Usertype)
        {
            Login log = new Login();
            if (Usertype == "SuperAdmin")
            {
                ViewBag.Title = "Super Admin Login";
            }
            else
            {
                ViewBag.Title = "Billing Login";
            }
            log.UserType = Usertype;
            return View(log);
        }

        public JsonResult LogProcess(Login logobj)
        {
            var response = "";

            try
            {
                switch (logobj.UserType)
                {
                    case "SuperAdmin":
                        response = SuperAdminLogin(logobj.Username, logobj.Password);
                        break;

                    case "Billing":
                        response = BillingLogin(logobj.Username, logobj.Password);
                        break;

                    default:
                        response = "";
                        break;
                }
            }
            catch
            {
                response = "";
            }
            string Url = string.Empty;
            string Responsetype = response == "" ? "Fail" : "Success";

            return Json(new { Url = response, Responsetype = Responsetype }, JsonRequestBehavior.AllowGet);
        }

        public string SuperAdminLogin(string username, string password)
        {
            string response = string.Empty;
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_SuperAdminLogin 'GET_LOGIN','','" + username + "','" + password + "'");
            if (dt.Rows.Count > 0)
            {
                HttpContext.Response.Cookies["SuperAdminusername"].Value = dt.Rows[0]["username"].ToString();
                HttpContext.Response.Cookies["SuperAdminusername"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["SuperAdminpasssword"].Value = dt.Rows[0]["password"].ToString();
                HttpContext.Response.Cookies["SuperAdminpasssword"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["SuperAdminName"].Value = dt.Rows[0]["Name"].ToString();
                HttpContext.Response.Cookies["SuperAdminName"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["SuperAdminId"].Value = dt.Rows[0]["Id"].ToString();
                HttpContext.Response.Cookies["SuperAdminId"].Expires = DateTime.Now.AddHours(1);

                response = "/Admin/index/";
            }
            else
            {
                response = "";
            }
            return response;
        }

        public string BillingLogin(string username, string password)
        {
            string response = string.Empty;
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_SuperAdminLogin 'GET_LOGIN','','" + username + "','" + password + "'");
            if (dt.Rows.Count > 0)
            {
                HttpContext.Response.Cookies["Billingusername"].Value = dt.Rows[0]["username"].ToString();
                HttpContext.Response.Cookies["Billingusername"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["Billingpasssword"].Value = dt.Rows[0]["password"].ToString();
                HttpContext.Response.Cookies["Billingpasssword"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["BillingName"].Value = dt.Rows[0]["Name"].ToString();
                HttpContext.Response.Cookies["BillingName"].Expires = DateTime.Now.AddHours(1);

                HttpContext.Response.Cookies["BillingId"].Value = dt.Rows[0]["Id"].ToString();
                HttpContext.Response.Cookies["BillingId"].Expires = DateTime.Now.AddHours(1);

                response = "/BillingDashboard/index/";
            }
            else
            {
                response = "";
            }
            return response;
        }
        #endregion

        #region Generic Forgot Password

        public JsonResult ForgotPassword(Login logobj)
        {
            DataTable dt = new DataTable();
            var response = "";

            try
            {
                switch (logobj.UserType)
                {
                    case "SuperAdmin":
                        dt = util.Display("Exec Proc_SuperAdminLogin 'FORGOT_PASSWORD','','','','" + logobj.Emailid + "'");
                        if (dt.Rows.Count > 0)
                        {
                            response = SendEmail(dt.Rows[0]["Name"].ToString(), dt.Rows[0]["Username"].ToString(), dt.Rows[0]["Password"].ToString(), logobj.UserType, dt.Rows[0]["Emailid"].ToString());
                        }
                        else
                        {
                            response = "";
                        }
                        break;

                    case "Billing":
                        dt = util.Display("Exec Proc_SuperAdminLogin 'FORGOT_PASSWORD','','','','" + logobj.Emailid + "'");
                        if (dt.Rows.Count > 0)
                        {
                            response = SendEmail(dt.Rows[0]["Name"].ToString(), dt.Rows[0]["Username"].ToString(), dt.Rows[0]["Password"].ToString(), logobj.UserType, dt.Rows[0]["Emailid"].ToString());
                        }
                        else
                        {
                            response = "";
                        }
                        break;

                    default:
                        response = "";
                        break;
                }
            }
            catch
            {
                response = "";
            }
            string Msg = string.Empty;
            string Responsetype = response == "" ? "Fail" : "Success";

            return Json(new { Msg = response, Responsetype = Responsetype }, JsonRequestBehavior.AllowGet);
        }

        public string SendEmail(string name, string userid, string password, string usertype, string ToEmailid)
        {
            string response = string.Empty;
            if (name != "")
            {
                StringBuilder sb = new StringBuilder();
                string Name = name;

                sb.Append("<table border='0' cellspacing='0' cellpadding='10' width='500' align='center' style='border: 1px solid #ccc; font-family: Arial, Helvetica, sans-serif; font-size: 14px; border-collapse: collapse; line-height: 20px;'>");
                sb.Append("<tr><td colspan='2' align='center'><img src='/Content/images/logo_Hafele.png' style='width: auto;max-height:100px;' /><br /><hr color='#04869a' /></td></tr>");
                sb.Append("<tr><td colspan='2'>Dear " + Name + ",<br /> Find your login details below :</td> </tr>");
                sb.Append("<tr bgcolor='#f4f4f4'><td width='90'>User Name:</td><td><strong> " + userid + " </strong> </td> </tr>");
                sb.Append("<tr bgcolor='#f4f4f4'><td>Password :</td><td><strong> " + password + " </strong> </td></tr>");
                sb.Append("<tr bgcolor='#f4f4f4'><td colspan='2' align='center' height='5'></td></tr>");
                sb.Append("<tr><td colspan='2' align='center' height='1'></td></tr>");
                sb.Append("<tr><td colspan='2'>Regards,<br /><strong><font color='#04869a'>Hafele</font></strong></td></tr>");
                sb.Append("<tr><td colspan='2' align='center' height='1'></td></tr>");
                sb.Append("</table>");

                String[] emailid = new String[] { ToEmailid };


                bool result = util.SendEmail(sb.ToString(), emailid, "Hafele Forgot Password", "", null);

                if (result)
                {
                    response = "sent";
                }
                else
                {
                    response = "";
                }              


            }
            else
            {
                response = "";
            }
            return response;
        }

        #endregion

        #region Generic Logout

        public ActionResult LogOut(string Usertype)
        {

            if (Usertype == "SuperAdmin")
            {
                if (Request.Cookies["SuperAdminusername"] != null && Request.Cookies["SuperAdminusername"] != null)
                {
                    HttpCookie myCookie = new HttpCookie("SuperAdminusername");
                    myCookie.Expires = DateTime.Now.AddDays(-1d);
                    Response.Cookies.Add(myCookie);

                    HttpCookie myCookie1 = new HttpCookie("SuperAdminpasssword");
                    myCookie1.Expires = DateTime.Now.AddDays(-1d);
                    Response.Cookies.Add(myCookie1);

                    HttpCookie myCookie2 = new HttpCookie("SuperAdminName");
                    myCookie1.Expires = DateTime.Now.AddDays(-1d);
                    Response.Cookies.Add(myCookie2);


Hafele_Onam/Hafele_Onam/Views/Shared/AdminMaster.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>
<head>
    <meta name="theme-color" content="#bfc2d1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://www.hafeleindia.com/hap-live/static/WFS/Haefele-HIN-Site/-/-/en_IN/images/favicons/favicon.ico" type="image/x-icon" />
    <title>@ViewBag.Title</title>
    @*<link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Content/Resource/website/images/logo.jpg")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Content/Resource/website/images/logo.jpg")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Content/Resource/website/images/logo.jpg")">*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    @Styles.Render("~/Admin/css1")
    @Scripts.Render("~/Admin/js1")
    @Styles.Render("~/Admin/css2")

    <!-- Icon font-->
    <link rel="stylesheet" href="~/Content/Resource/website/css/icon-font.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Resource/website/css/flaticon.css">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Content("~/Admin/Index/")" class="site_title">
                            @*<i class="fa fa-paw"></i>*@
                            <img src="@Url.Content("~/Content/images/logo_Hafele.png")" alt="Image Not Available" class="img-circle profile_img" style="height:34px;width:34px;margin-top: 2px;margin-left: 1px;">
                            <span>Super Admin</span>
                        </a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="@Url.Content("~/Content/images/logo_Hafele.png")" alt="Image Not Available" class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>Hafele</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li><a href="~/Admin/Index/"><i class="fa fa-home"></i>Dashboard </a></li>
                                <li>
                                    <a href="~/Admin/Offers_Leads"><i class="fa fa-edit"></i>Offers Leads</a>
                             
                                </li>
                             
                            </ul>
                        </div>


                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small" style="background-color: #4b5f71; padding: 15px 0px 0px 0px;">
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="@Url.Content("~/Content/images/img.jpg")" alt="Image not Available">User

                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="@Url.Content("~/Admin/UpdateProfile")">Profile</a></li>
                                    <li><a href="@Url.Content("~/Admin/ChangePassword")">Change Password</a></li>
                                    <li><a href="@Url.Action("LogOut", "Login", new { @Usertype = "SuperAdmin" })"><i class="fa fa-sign-out pull-right"></i>Log Out</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            @RenderBody()

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    © @DateTime.Now.Year  <a href="#">Hafele.</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    @Scripts.Render("~/Admin/js2")

</body>
</html>